### ISSUE TITLE
Implement unified results and pipeline joining similar to travis-after-all

### ISSUE THREAD

**Issue by ssbarnea** [ryanhiebert/tox-travis#13]
Currently the `tox-travis` does not allow us to make a release if ALL travis jobs succeeded. People are probably using the travis-after-all approach on this. 

Still, it would be extremely helpful for any Python projects to integrate this into travis-tox as we do want to be able to consolidate the results of different executions and get a final single build report and do an automatic release if the outcome is positive.

**Comment by ryanhiebert** [comment]
This is an interesting idea. At first I was hesitant to add this hack, but I think with some care this can be a useful feature to have, and can be a boon for people to start using `tox-travis`. I'm not sure when I'll get to it, but after a quick read of travis-after-all, I'm inclined to think that a port of that code is probably a reasonable approach for the first release of this feature.

Usage would probably be something like this, which would run the tox env `after`:

```sh
tox --travis-after -e after
```

https://github.com/travis-ci/travis-ci/issues/929 (the issue on Travis CI for a native version of this feature) has one comment suggesting that a _before_ version would also be useful. Unfortunately, I don't think that can be reliably implemented, because race conditions when interacting with the API are much more likely in that case.

**Comment by ssbarnea** [comment]
Yep. It is really annoying that Travis locked this thread. I am trying to make them re-open it and to find an official fix for it. Twitter seems like a way to do this https://twitter.com/sbarnea/status/726783813272133633

**Comment by ryanhiebert** [comment]
This will require including an extra dependency, requests. It's not needed for the current functionality of tox-travis, so it makes me wonder if it should be opt-in to have the extra dependencies needed for this capability. This would be done with a extras require section, so the options for installation are:

```sh
# The same as it is now, just with more dependencies
pip install tox-travis
```

or

```
# The extra dependencies are explicitly requested
pip install tox-travis[after]
```

Which is better?

**Comment by ssbarnea** [comment]
I prefer the first option, extras are hard to remember but that's a personal preference.

**Comment by reece** [comment]
When using tox-travis and pypi deployments, travis attempts to deploy when each environment succeeds. I want it to deploy only when *all* environments succeed.

I think my observation is caused by the lack of a gather/join described in this issue thread. Is that correct? Is there a way to configure tox/tox-travis to deploy once?

One comment on [my StackOverflow question](https://stackoverflow.com/questions/39341486/) suggests that it's not possible.

**Comment by ryanhiebert** [comment]
To the best of my knowledge, it's not possible natively with Travis, and it's not currently supported by tox-travis. This issue is tracking that feature, and I think it could be a very nice feature to have in tox-travis, so I'd be happy for someone to pick it up.

With some pain, I think you could use travis-after-all to do this. I don't do that for my automated deployments. Instead, I just have it automatically deploy on tags, and tell it to only deploy for one of the test variants I have. This is OK, because I'm pretty confident in the test results, because I make sure that pull requests pass before I merge them. Of course, there are ways this could fail, but it work fine most of the time, and that's been good enough for me so far.
