### ISSUE TITLE
Manage virtualenv dependency for py32

### ISSUE THREAD

**Issue by jayvdb** [ryanhiebert/tox-travis#17]
tox depends on virtualenv, and virtualenv 14+ is busted on Python 3.2
While travis provides '3.2', tox-travis should also support Python 3.2, and it can make that simpler by adding a dependency on `virtualenv<14` only on Python 3.2.

Then `pip install tox-travis` will install tox and a suitable version of virtualenv .

A [similar bug](https://bitbucket.org/hpk42/tox/issues/323) exists upstream in `tox`, but they do not have a strong reason to support Python 3.2, while `tox-travis` does.

**Comment by ryanhiebert** [comment]
I'm of the opinion that nobody should be using or supporting Python 3.2 anymore. Virtualenv doesn't support 3.2, so tox doesn't support 3.2, so tox-travis doesn't support 3.2. Because of that, I've removed Python 3.2 from the tox-travis build matrix.

Practically, I see the benefit of having the virtualenv limit for Python 3.2. Unfortunately, unless I want to limit to that virtualenv for _every_ version of Python, I either have to leave it to the user to fix, or I have to give up the universal wheel, which I'd really rather not do.

Unless there's more uproar about this, my preferred approach to allowing Python 3.2 to run correctly is to have the install line look like this:

```python
install: pip install tox-travis virtualenv<14
```

If there were a way that I could add that dependency for Python 3.2 only, and without forcing an old version of virtualenv on other Pythons _or_ dropping the universal wheels, then I'd be all for it. If that's not possible, I think the best approach is to document the above workaround, along with a note that I don't encourage 3.2 support, and tox-travis isn't tested on 3.2.

**Comment by jayvdb** [comment]
It is possible to have version specific dependencies with universal wheels. The tox setup.py is the best example implementation that I have seen.

**Comment by ryanhiebert** [comment]
Thank you for letting me know about this. The approach taken there works for me.

**Comment by ryanhiebert** [comment]
I've created a pull request with 3.2 support added back. Thank you for pointing out the solution, @jayvdb . Would you mind reviewing the PR when you have some time?
