### ISSUE TITLE
PyPy3 5.2

### ISSUE THREAD

**Issue by jayvdb** [ryanhiebert/tox-travis#22]
See https://github.com/travis-ci/travis-ci/issues/6277#issuecomment-232161722
 and https://bitbucket.org/hpk42/tox/issues/345/pypy3-52

I have a patch almost ready to roll, the outstanding problem is how this release should be treated in tox-travis.

Currently I have it mapping to `pypy3`, which is the worst option IMO, but I am not keen on defining new test environment factors that dont exist outside of Travis.  My preference would be to wait to see if `tox` defines a better strategy on that issue.

**Comment by ryanhiebert** [comment]
I agree with your preference. We need to see what tox and Travis do, because we can't guide them, but merely follow their lead.

It does make me remember that pypy3 was (probably) dropped when Python 3.2 was dropped, so that likely needs to be added back to the build matrix with the changes from #20 .

**Comment by jayvdb** [comment]
Raised an upsteam task for what I hope is the last problem : https://github.com/travis-ci/travis-ci/issues/6304 . I have a workaround which we can use, but maybe it can be fixed upstream promptly.

**Comment by ryanhiebert** [comment]
This is fixed by #24. It'll be in the next release.

**Comment by ryanhiebert** [comment]
Version 0.5 is out!

**Comment by jayvdb** [comment]
Ok. Im up and crossing my fingers and toes.
