### ISSUE TITLE
builds only work on python 2.7

### ISSUE THREAD

**Issue by denfromufa** [ryanhiebert/tox-travis#29]
I'm setting up pythonnet builds on both Linux and OSX using Travis CI. Previously the builds were working fine under Linux only, but with tox and tox-travis I'm only able to build on Linux 2.7

```
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/pythonnet/pythonnet/.tox/py33/log/py33-1.log
ERROR: actionid: py33
```

Here are the successful and failing builds:
https://travis-ci.org/pythonnet/pythonnet/jobs/163293730
https://travis-ci.org/pythonnet/pythonnet/jobs/163293731

I will start looking into Mac builds later.

**Comment by ryanhiebert** [comment]
Sorry it's taken me so long to respond, this got lost in my inbox.

The problem is that you're not running tox quite right. In particular, you need to get your configuration (in `tox.ini`) to run properly before you can use tox-travis, because tox-travis just simplifies using tox on travis.

Once you can just run `tox` to run your tests, then you can work on your `.travis.yml`. Make sure that your script is `tox`. It's the same thing that you'd run locally, but tox-travis does a little magic to help it determine which tox envs to run automatically.

Note also that for what you have in the `tox:travis` section of your `tox.ini`, you don't need that. Those are all the default mappings anyway. Also remember that those have _no effect_ except on Travis runners.

I hope that helps you figure it out!

**Comment by denfromufa** [comment]
Actually the issue turned to be this one, you can see my case at the bottom:

https://github.com/tox-dev/tox/issues/245

So looks like our previous setup in pythonnet with just relying on
virtualenv for Python versions provided on Linux by Travis CI does not work
when tox is handling python versions due to custom files in setup.py.
The only reason why I added tox and pyenv is to handle Mac OSX and Linux
with Travis CI at the same time.

But I think to switch to this setup provided by Matthew Brett and PEP 513
that I found out later:

https://github.com/matthew-brett/multibuild

**Comment by ryanhiebert** [comment]
OK, cool. If there's something that tox-travis could reasonably do to make this easier, please open a new issue to let me know!
