### ISSUE TITLE
Support other Travis matrix factors than Python version

### ISSUE THREAD

**Issue by henriquebastos** [ryanhiebert/tox-travis#4]
Hi! This is an awesome lib. Thank you very much!!!

Is it possible to map 1 Travis env to 1 Tox env?

I have 6 env on Tox (python version x django versions) and 3 on Travis (1 for each python version).

With `tox-travis` I could only separate by the python versions. Did I missed anything?

This is `tox.ini`:

``` ini
[tox]
envlist = py{27,35}-django{18,19}, py{27,34}-django17

[tox:travis]
2.7 = py27
3.4 = py34
3.5 = py35

[testenv]
deps =
    django17: Django>=1.7,<1.8
    django18: Django>=1.8,<1.9
    django19: Django>=1.9,<1.10
    django-nose==1.4.2
    nose==1.3.7
commands = python runtests.py
```

And my `.travis.yml` is:

``` yml
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -q tox-travis
script:
  - tox
```

**Comment by ryanhiebert** [comment]
You didn't miss anything, unfortunately. I have a potential plan on how to implement this, but I've not gotten it all worked out quite yet. Let me quickly write it up here, and see if you can give me some feedback on the design.

-----------

Currently, `tox-travis` will run all the environments that match all the factors given in the `tox:travis` section of the `tox.ini` file, defaulting with just matching the Python versions.

Under the hood, this looks at the `TRAVIS_PYTHON_VERSION` environment variable, and interpreting it. If `TRAVIS_PYTHON_VERSION` is `3.4`, then it will use `py34` as the target env pattern, so anything with `py34` as a factor will run.

My thought for adding additional knowledge of the matrix would be to use the environment variable name as the key in the `tox:travis` section, and use tox-style filters to handle them. So the current default `tox:travis` section looks like this (only considering two versions of python, though there are more it supports):

```ini
[tox:travis]
3.5 = py35
pypy3 = pypy3
```

With the new mode, it would look like this (though the previous example would still work for backward compatibility):

```ini
[tox:travis]
TRAVIS_PYTHON_VERSION =
    3.5: py35
    pypy3: pypy3
```

Making that pattern support env var factors would be easy:

```ini
[tox:travis]
DJANGO =
    1.7: django17
    1.8: django18
    1.9: django19
```

Then you could configure the `DJANGO` environment variable in your `.travis.yml`, and have it run the correct environments. You'd still need to make sure to exclude the Python/Django versions that weren't compatible, though.

---------

The downside to this approach is that, because of the `:` being a delimiter in the config, you can't have any values for your environment variables contain `:`. Unfortunately, I'm not seeing a better design ATM that eliminates that kind of a concern. You also can't have any env factors that have `:`, but that's not a concern because that causes issues elsewhere in tox, like reading tox configuration.

So, what do you think of that approach? Would it match your intuition, and is the no `:` restriction acceptable?

**Comment by henriquebastos** [comment]
Cool! I think using travis `env` would solve it. :)

The `:` restriction doesn't seem a problem at all.

So considering this, I think it would be intuitive to adapt my config files above to:

```yml
language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
include:
  - python: 2.7
    DJANGO=1.7
  - python: 3.4
    DJANGO=1.7
install:
  - pip install -q tox-travis
script:
  - tox
```

So now I have 6 build entries on my travis matrix.

Then I could map it on `[tox:travis]`:

```ini
[tox]
envlist = py{27,35}-django{18,19}, py{27,34}-django17

[tox:travis]
TRAVIS_PYTHON_VERSION =
    2.7: py27
    3.4: py34
    3.5: py35
DJANGO =
    1.7: django17
    1.8: django18
    1.9: django19

[testenv]
deps =
    django17: Django>=1.7,<1.8
    django18: Django>=1.8,<1.9
    django19: Django>=1.9,<1.10
    django-nose==1.4.2
    nose==1.3.7
commands = python runtests.py
```

**Comment by henriquebastos** [comment]
And forcing the use of the section `[tox:travis]` with the *actual* travis envvar names would also enable us to automagically generate `.travis.yml` files for `tox-travis`.

**Comment by ryanhiebert** [comment]
Your `.travis.yml` looks strange to me, and I'm not sure if it's correct syntax or not (I mean, really, who knows what correct YAML is), but the idea certainly looks like what I intend.

The `.travis.yml` file generation sounds like a very interesting idea, one I hadn't thought of. It seems like there may be some sticky corners, though.

**Comment by ryanhiebert** [comment]
Also, remember that the `TRAVIS_PYTHON_VERSION` you have there will be the default, just like the `2.7`, `3.4`, and `3.5` keys you had in your original post are currently the default, and aren't needed.

**Comment by henriquebastos** [comment]
Yes the default would help. I was just trying to make an explicit and complete example.

About the yml generation, it should not be a complete solution. If it works on basic matrix 80% of the time it's a nice start/boilerplate to users improve after.

**Comment by ryanhiebert** [comment]
I've created a new issue for discussion of the `.travis.yml` file auto-generation. This one will track this new feature I sketched out.

**Comment by nueverest** [comment]
Will `os` choices also be taken into account?

    os:
        - linux
        - osx

The matrix options are [more complicated](https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)) in that case.

**Comment by ryanhiebert** [comment]
It doesn't currently, but I'm open to the possibility.

**Comment by ssbarnea** [comment]
@nueverest Have you managed to test Python projects on both linux and osx with Travis? When I enable OSX it does not allow me to use Python as it seems to be reported as not supported on osx, even if we all know that OSX comes with Python too.

Please do not ignore the matrix support on travis.

**Comment by ryanhiebert** [comment]
@nueverest : The examples for multi-os support show using `TOXENV`. That'll work just fine, since tox-travis won't affect anything in that case. Unfortunately, that loses the benefits of tox-travis on that platform. Because we use `sys.version_info` to figure out which Python we're under, there's not a good way to use a particular python version.

Earlier in this thread I mentioned using `PYTHON_TRAVIS_VERSION` as the environment variable that we use to determine the python version. We don't use that variable anymore, because I wanted to figure out which python version was active based on `sys.version_info`. This os feature really throws a wrench into that. I may have to switch back to using `PYTHON_TRAVIS_VERSION`, so that you can at least set it manually.
