### ISSUE TITLE
Pass on allowed failures to Travis

### ISSUE THREAD

**Issue by Bouke** [ryanhiebert/tox-travis#48]
Currently I have a few environments that are allowed to fail. Without combining travis and tox these builds would show up as failed build jobs, but the overall build would succeed. 

However once combining tox and travis all the build jobs will show up as success; as `tox` will no longer report a failure to travis, in fact swallowing errors ([example][0]). So in order to report these failures to travis, I could remove `allowed_failures` from `tox.ini`. However when running tox locally, tox would also report those environments as failures.

Is there a way to achieve the following?

* When running with tox-travis, all failures from tox are reported to travis, effectively by-passing `allowed_failures`; (and it's up to the build matrix in `.travis.yml` to allow those failures).
* When running tox locally, take `allowed_failures` into account.

[0]: https://travis-ci.org/Bouke/django-user-sessions/jobs/189735034

**Comment by rpkilby** [comment]
This seems like it *should* be possible. tox-travis does nothing when running locally, so `ignore_outcome` would be obeyed. For CI, it would need to:

- parse the tox.ini for which envs `ignore_outcome`.
- muck with the tox run such that `ignore_outcome` is not obeyed.

The former should be feasible (I think `deps` are parsed for specialized `toxenv`s). Not sure what the muckability of the latter would be though.

Maybe this feature could be enabled (default to disabled) with an `obey_outcomes` option?

**Comment by ryanhiebert** [comment]
The muckability of Tox in this regard is probably the main implementation unknown. I suspect that, if nothing better, we could likely monkeypatch an appropriate method to give ourselves a hook to do this.

I don't think we'll need to parse the `tox.ini` for `ignore_outcomes`. We should be able to just make sure it's set for all the envs we're running unconditionally.

AFA a name, I like `obey_outcomes`, but I wonder if it might leave the impression that it's obeying the _configuration_ for outcomes (that is, respecting the `ignore_outcomes` setting) rather than disobeying the configuration. Perhaps `unignore_outcomes` would be clearer?

**Comment by rpkilby** [comment]
Or perhaps... `ignore_ignore_outcomes`?

**Comment by ryanhiebert** [comment]
I guess it would meet the "clearer" idea, but man it's ugly. 😬

**Comment by ryanhiebert** [comment]
`obey_outcomes` is the nicest name. Perhaps `force_obey_outcomes`?

**Comment by ryanhiebert** [comment]
or `force_use_outcomes`

**Comment by rpkilby** [comment]
> I guess it would meet the "clearer" idea, but man it's ugly. 

I was not serious 😄 

Definitely prefer `obey_outcomes` to `force_use_outcomes`, but both make sense to me.
- Docs would explain the actual behavior and why it's useful.
- I'm not too worried about the potential name confusion, but if too many people find it confusing, the setting name can always be changed later.

**Comment by Bouke** [comment]
Being the cause of all of this, I've looked into making this feature happen. I'm currently testing, will keep you posted!
