### ISSUE TITLE
Incorrect/optimistic env matching?

### ISSUE THREAD

**Issue by rpkilby** [ryanhiebert/tox-travis#55]
See https://github.com/tomchristie/django-rest-framework/pull/4842 for more info. In short, the `.travis.yml` file had a typo, including a build against django 1.18. However, it somehow matched against django 1.8.

Have we reached a point where interpreters account for typos?? Truly, this is a magical time. :smile:

**Comment by rpkilby** [comment]
Here is the a [build](https://travis-ci.org/tomchristie/django-rest-framework/jobs/194674508) affected by the bug.

**Comment by ryanhiebert** [comment]
Wow. That's sure looks like broken behavior, and I don't know yet how it happened. Thanks for reporting.

**Comment by rpkilby** [comment]
My guess is that it has something to do with the regex? 1.8 is in 1.18?

**Comment by rpkilby** [comment]
Actually yeah. There is a comment indicating that single digits are assumed. https://github.com/ryanhiebert/tox-travis/blob/0.8/src/tox_travis/toxenv.py#L106-L107

**Comment by ryanhiebert** [comment]
The single digits are, unless I got something badly wrong, just the python version. Guido doesn't care for double digits, which is part of what makes 2.7.10 so weird for Python versions.

**Comment by ryanhiebert** [comment]
I apologize for the delay figuring out what happened here.

What happened here is that the Python version here (3.3) had only one Django version to run under it (Django 1.8). If the Python version had been 3.4, there were other envs that would have run as well, and you would have seen other Django versions run as well.

When the environment variable doesn't match anything, it simply ignores the limits put in place by that configuration, and will run everything that matches the other variants it does know about.

This is the way it was designed, and though I think it's a bit confusing, I think it's probably the correct behavior with this kind of misconfiguration. There are cases where you may wish to only watch for certain values of an environment variable, but ignore others. Rather than raise an error, it should run more than expected.

This is particularly true with the odd environment variables that Travis uses for dealing with multiple OSs. Unfortunately the nice `python` key doesn't work, and you have to contend with weird variants using the `generic` language, and watch for which `os` is being used.

Moral of the story is that if the configuration doesn't match, you'll end up with _extra_ environments running, but it is not magically guessing which one you really meant. By choosing to not guess, it ended up running too many jobs, which has seemed so far to be a reasonable choice to me.

If you disagree, feel free to make your case. I'm listening.

**Comment by rpkilby** [comment]
The above makes sense, although it might be useful to have a "strict" matching mode. So far, I've used tox-travis to reduce the effort in maintaining parity between the travis and tox build matrixes. In my case, a travis job should only ever run a single tox env and the lack of a match represents a configuration error. The current behavior masks this by allowing the job to continue.
